### ISSUE TITLE
Hook URL with custom data

### ISSUE THREAD

**Issue by zimini** [wildbit/postmark-gem#44]
Guys, I just wondering do you support custom Tags? We look like to include some extra information in Tag that we don't want our internal support team users to see on Postmark. For example: Tag: invite. We would also like to have Tag: invite {user_id = 123, company_id = 987}.

We have number of apps, one app is responsible for the email send process, another API app is responsible to get webhook bounce/opens and store it. They use separate DBs. Our API would then use the extra information in the Tag that is returned from Postmark. We would like to hook Postmark straight to the API without saving data in between (message_id), so we need to save custom data but do not mess the Tag itself.

**Comment by temochka** [comment]
Hi @zimini,

Unfortunately it is currently not possible to attach any kind of metadata to messages sent via Postmark except for the tag field. There are headers, but they’re not included in webhook JSON. At this point we recommend persisting data on your end and using message ID to tie pieces together. Also we don’t recommend putting arbitrary data in the tag field, because our stats and web interface are not well suited for this use case (it will try to aggregate stats by every unique tag). Please let me know if you have any questions.

**Comment by zimini** [comment]
Hi @temochka ,

Yep, we had thought about those issues alright but hoping there was a way around the metadata.

Thanks for your time!
