### ISSUE TITLE
Add documentation for error handling

### ISSUE THREAD

**Issue by nruth** [wildbit/postmark-gem#53]
I couldn't find anything in the readme or postmark-rails readme about error classes, which makes this hard to debug from a delayed-job failure.

Things like:

```
You tried to send to a recipient that has been marked as inactive.
Found inactive addresses: [redacted].
Inactive recipients are ones that have generated a hard bounce or a spam complaint. 
/app/vendor/bundle/ruby/2.3.0/gems/postmark-1.8.1/lib/postmark/http_client.rb:75:in `handle_response'
```

This is in Rails 4.2 using the postmark-rails gem and `action_mailer.delivery_method   = :postmark`.

I want to be able to catch the error so they don't keep re-trying and clog up the work queue.

**Comment by temochka** [comment]
Hi @nruth,

The base class for all gem exceptions is `Postmark::DeliveryError`, so you can rescue from that to "catch them all". The gem will also "leak" some exceptions from the underlying net/http library, documented in [Ruby docs](http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-HTTP+Response+Classes). You can see the full list of available exceptions in [postmark.rb](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark.rb#L22). Unfortunately, the existing design is not ideal. Persistent errors are currently mixed with transient ones. For example, `TimeoutError` or `InternalServerError` are almost definitely transient, while something like `InvalidApiKeyError` certainly isn’t.

Among all these, `InvalidMessageError` is somewhat special, because there is a possible action that you can do when it occurs (like in case with your example). If `InvalidMessageError` was thrown with [#error_code == 406](http://developer.postmarkapp.com/developer-api-overview.html#error-codes), you might want to either mark the address as "do not send to" in your internal database or, alternatively, use the [bounces API](https://github.com/wildbit/postmark-gem#working-with-bounces) to reactivate that address (if you’re sure the issue was resolved).

I’ll leave this issue open to update the docs with this information.

**Comment by inopinatus** [comment]
It's worth noting that you won't get an InvalidMessageError due to inactive recipients, unless *all* the recipients are inactive.

In the trivial case of a single recipient, no problem, but if you Cc or Bcc this will probably mask the issue.

In my case this means I can't rely on the code 406 InvalidErrorMessage mechanism as a notification path, because we run a SaaS marketplace and some messages are sent to both parties in a transaction. Fortunately for us, Postmark have bounce webhooks.

**Comment by temochka** [comment]
Starting with version `1.11.0`, we introduced more useful exception types and added a detailed example of error handling to the [README](https://github.com/wildbit/postmark-gem/tree/v1.11.0#error-handling).

**Comment by mech** [comment]
Want to ask if @inopinatus is correct in saying that if any inactive emails was inside any CC or BCC, PostMark will not throw the `InactiveRecipientError` exception if **all** of them are not inactive.

**Comment by temochka** [comment]
Hi @mech, yes this is correct. If you’re using the `postmark` gem and the `ApiClient#deliver` call, you get back Postmark response as a Ruby hash:

``` ruby
response = client.deliver(from: 'sender@wildbit.com', to: %w(sender@wildbit.com nothing@wildbit.com), subject: 'Subject', text_body: 'Test')
# {:to=>"sender@wildbit.com, nothing@wildbit.com", :submitted_at=>"2018-07-02T16:35:02.3692155-04:00", :message_id=>"cb2a9f16-7feb-4cb3-993c-82ea8f1a5af8", :error_code=>0, :message=>"Message OK, but will not deliver to these inactive addresses: nothing@wildbit.com. Inactive recipients are ones that have generated a hard bounce or a spam complaint."}
```

In this case, if you want to handle inactive recipients, you can use the following trick:

``` ruby
Postmark::InactiveRecipientError.parse_recipients(response[:message])
# => ["nothing@wildbit.com"] 
```

**Comment by mech** [comment]
I am actually using postmark-rails and catch it using `rescue_from`. I hope the `recipients` given was the same:

```ruby
rescue_from(Postmark::InactiveRecipientError) do |e|
  emails_rejected(emails: e.recipients)
  notify(exception: e, recipients: e.recipients)
end
```

which looks like it is 😃

**Comment by temochka** [comment]
Yeah, that should work great for the case when all message recipients are inactive.

**Comment by naw** [comment]
It seems odd for the postmark API server to return success for an email that is delivered to one recipient, but is known to have _not_ been delivered to another recipient.

**Comment by temochka** [comment]
@naw I’m afraid, I’m the only one who’s getting notified about this and I don’t even work at Postmark anymore. Please email support@postmarkapp.com and the smart folks there will be thrilled to help you with the right pattern for handling inactive recipient errors.

That said... If I remember correctly (**assume I don’t**), the whole idea behind the inactive recipient list is that whenever Postmark receives a hard bounce or a spam complaint, it deactivates the recipient address for your server and then notifies your app about it via the bounce web hook. Ideally, your app should process that request and not attempt further deliveries for such recipient because they will be rejected. Most apps never set up the bounce hook though, so Postmark’s default has to account for that. And here you have it: all things considered, "accept emails for the active recipients, drop the inactive recipients" is the safest choice, because the alternatives are:

* accept the messages for active recipients but throw an exception (apps may retry and cause duplicates for the "good" recipients, which is potentially embarrassing)
* throw an exception and reject messages for all recipients (unnecessary backpressure that the clients may not be ready to handle, and certain kinds of inactive recipients cannot be re-activated via the API so no amount of retries will help)

I think that covers it, but if not, email support@postmarkapp.com. Good luck!
