### ISSUE TITLE
`track_links` symbol not converted to postmark string in `MailMessageConverter` (through actionmail/postmark-rails)

### ISSUE THREAD

**Issue by aeris** [wildbit/postmark-gem#60]
Hi,

I found what it seems to be a bug on `MailMessageConverter`.
From https://github.com/wildbit/postmark-rails/, if you send a mail with links tracking enabled but with the symbol form (`:html_only` for example), value is not converted to postmark supported text form (`HtmlOnly` here).

Unit tests say the opposite, see [here](https://github.com/wildbit/postmark-gem/blob/master/spec/unit/postmark/mail_message_converter_spec.rb#L278-L285), but in practice, using code like `SuchMailer.wow(track_opens: true, track_links: :html_and_text).deliver_now` fails silently (no error but no postmark delivery).

From what I understand, through actionmailer, the tracking link is not set by the [`Mail#tracking_link=`](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/message_extensions/mail.rb#L23-L25) method, and so not converted on the fly.
I need to modify [this line](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/mail_message_converter.rb#L34) to `'TrackLinks' => (::Postmark::Inflector.to_postmark(@message.track_links) unless @message.track_links.empty?)` to trigger the conversion and allow the delivery.
Seems `track_opens` is correctly converted to boolean at this time, but not `track_links`.

Regards,

**Comment by temochka** [comment]
Hi @aeris!

Sorry, I’m not sure I follow you here:

> using code like SuchMailer.wow(track_opens: true, track_links: :html_and_text).deliver_now fails silently (no error but no postmark delivery).

Could you please provide the code for `SuchMailer`? Normally, mailer method arguments are not passed to the underlying postmark gem. The method would have to explicitly proxy such arguments to the `mail` call (is this the case?). Also, depending on your Rails version (and the `mail` gem version), you might have to set `track_opens` to a string `'true'` (as described [here](https://github.com/wildbit/postmark-rails#tracking-opens-and-tagging-your-deliveries)).

That said, I don’t see how missing any of these flags could result in "no postmark delivery". I’ll need more details here to give a helpful reply, sorry.

**Comment by aeris** [comment]
Here is a project to show the problem : https://github.com/aeris/postmark-gem-issue-60

If you run `POSTMARK_TOKEN=POSTMARK_API_TEST bin/send-email.rb from@example.org to@example.org`, failure on `SuchMailer.wow(from, to, track_links: :html_and_text).deliver_now
` and `SuchMailer.wow(from, to, track_opens: true, track_links: :html_and_text).deliver_now`.
With my fix on `mail_message_converter.rb`, all cases are OK.

Note that `SuchMailer.wow(from, to, track_opens: true).deliver_now` is already valid, because [conversion is done](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/mail_message_converter.rb#L33) for boolean to string in `#track_opens`.
`#track_opens` and `#track_links` not coherent at this time, only the first is converted to valid postmark string, not the second.

For my delivery problem, I think this is because I use `config.action_mailer.raise_delivery_errors = false` on dev environment, and so delivery failure is not raise. No trouble on prod.

**Comment by temochka** [comment]
Thank you for such a detailed explanation @aeris! I see what you mean now. It’s our fault that we never documented the `track_links` functionality for the Rails gem. Currently it’s assumed that you’d specify values as strings in camel case (`HtmlAndText`, `HtmlOnly`, etc.). However, It’d definitely be nicer and more consistent with the `postmark` gem if the conversions were performed automatically.

On the technical side, the problem here is that the options passed to `ActionMailer::Base#mail` are assigned directly to message headers. This is different than calling [message.track_links=](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/message_extensions/mail.rb#L23). It might make sense to move the conversion logic from writer to [reader](https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/message_extensions/mail.rb#L18). That would cover both cases, but additional testing is required. The proposed approach of patching `MailMessageConverter` also seems viable, but this should also be tested for regressions on all supported versions of Ruby, Mail, and ActionMailer.

I’m going to keep this issue open until we can either update the docs or patch the `postmark` gem to better handle this case. In the meantime, I suggest using camel cased values expected by the API.
