### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by briankerr** [wildbit/postmark-gem#74]
The email message's Message-ID field has to follow a certain format to be valid, as described in [RFC5322](https://tools.ietf.org/html/rfc5322). If the message ID Postmark sets doesn't this format, there'll be a header validation error.

**Comment by ibalosh** [comment]
hey @briankerr , could you share bit more details what this issue is about?

**Comment by ibalosh** [comment]
Message-ID is not dependent on library but Postmark,

**Comment by espen** [comment]
@ibalosh I'm the one who reported this to customer service. It's a bug in your email sending where you do not follow rfc5322 when generating message-id. This results in a problem for the Mail gem which requires message-id to be formatted according to the RFC.

> Hey Espen,
> 
> Thank you for reporting this! After some investigation, this is a bug on our end. We've opened an issue in the GitHub project to publicly track this, and I hope we get to fixing it soon! It might not be immediate as our internal maintainer for that project is on PTO this week.

**Comment by ibalosh** [comment]
Hi @espen 

could you share bit more details, ideally an example regarding this issue? I am trying to isolate the source of the problem since it doesn't seem like an issue with the gem. 

If so, I will move it to our backlog in our ticketing system to check the Postmark app sender service with the dev team.

**Comment by espen** [comment]
It's not a gem problem. I reported it to customer support and they (@briankerr) created this issue.

The problem is that the email you send creates a GUID like ID: `9ab1f755-3892-4fe7-80af-409657df05b3`. It should follow the RFC as described in the Mail gem [here](https://github.com/mikel/mail/blob/6bc16b4bce4fe280b19523c939b14a30e32a8ba4/lib/mail/fields/message_id_field.rb). When it is not ActionMailer will give an error. It is only when using ActionMailer directly this occurs. I'm surprised this haven't resulted in other problems for servers getting email from Postmark.

Example:
```ruby
email = ActionMailer::Base.mail(from: "foo@exampler.org", to: "bar@example.org", subject: "Hello", body: "Foo")
```

This will send the email but give an error in email.errors. Thus I am unable to verify that the email was sent.

**Comment by ibalosh** [comment]
Got it, thanks for the details @espen 

I think I found out what could cause this. I will see to check it out and fix this week or next one the latest.

**Comment by ibalosh** [comment]
Hi @espen 

I released a small patch today. Let me know if it solves the issue. To try it make sure to use version  1.17.0 of the gem.

**Comment by espen** [comment]
Did a quick test here and looks like this is working as expected now :) 👍
