### ISSUE TITLE
Extremely long POST request

### ISSUE THREAD

**Issue by jbarber** [wildbit/postmark-gem#75]
Apologies if this isn't the right forum.

We use the postmark-rails gem to send mail. Earlier today we had an issue where it appears (from New Relic) that mail delivery spent 975 seconds in a POST request to api.postmark.com.

This coincides roughly with an incident in the postmark service (https://status.postmarkapp.com/incidents/6862) - which is fine - but why did the POST request take 975 seconds and not timeout earlier?

From my reading of the gem, it uses Net::HTTP and from TFM the default timeouts for Net::HTTP all appear around the 60 seconds mark - so I'd expect the POST to have died a lot sooner.

I care because this happened in a background worker that because it was stuck for 975 seconds caused all kinds of alarms to fire - and if possible I'd like to not fire the alarms in the future.

**Comment by temochka** [comment]
Hey @jbarber. If I had to guess, it’s DNS. (Because it’s always DNS 🙃). The [default YARV implementation of TCPSocket](https://github.com/ruby/ruby/blob/d48783bb0236db505fe1205d1d9822309de53a36/ext/socket/tcpsocket.c#L45) (used internally by Net::HTTP) relies on a deprecated DNS resolution method that blocks the entire VM, so it’s “immune” to the `open_timeout` setting. Even if you wrap the entire call to Postmark (or any other HTTP API) in a timeout, it can still get stuck for a long time. Not sure if we can do something about this aside from switching away from net/http, which comes with its own problems.
