### ISSUE TITLE
`Error parsing 'To': Unclosed quoted string` with an unusual but apparently valid address.

### ISSUE THREAD

**Issue by jarthod** [wildbit/postmark-gem#95]
Hi, I'm having a little problem with a slightly complex address format where the login contains slashes and back-slashes.
I'm using `Mail::Address` to format the email properly (which escapes the backslashes and adds the quotes), so far it looks correct to me but then when trying to send with postmark I get a `Error parsing 'To': Unclosed quoted string`.
The address display name causing trouble here is `//UwU\\`, see reproduction script:

```ruby
require 'postmark'
require 'mail'

a = Mail::Address.new("adrien@updown.io")
a.display_name = '//UwU\\\\'
puts a.display_name
# //UwU\\
puts a.format
# "//UwU\\\\" <adrien@updown.io>

server_token = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
client = Postmark::ApiClient.new(server_token, http_open_timeout: 15, http_ssl_version: :TLSv1_2)
client.deliver(from: 'system@updown.io', to: a.format, subject: 'test', text_body: 'test')
# Traceback (most recent call last):
#   8: from postmark_test.rb:11:in `<main>'
#   7: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/api_client.rb:14:in `deliver'
#   6: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/client.rb:39:in `with_retries'
#   5: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/api_client.rb:15:in `block in deliver'
#   4: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/http_client.rb:33:in `post'
#   3: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/http_client.rb:92:in `do_request'
#   2: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/http_client.rb:92:in `synchronize'
#   1: from /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/http_client.rb:93:in `block in do_request'
# /home/bigbourin/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/postmark-1.21.1/lib/postmark/http_client.rb:79:in `handle_response': Error parsing 'To': Unclosed quoted string: "//UwU\\\\" <adrien@updown.io> (Postmark::ApiInputError)
```

I'm not sure where's the problem here, if it's the gem that is not properly encoding or the server which is not properly decoding this, the formatted address looks valid to me, the quoted string is closed. http://sphinx.mythic-beasts.com/~pdw/cgi-bin/emailvalidate says it is a valid RFC822 email address also.

I'm using `ruby 2.6.4` and `postmark 1.21.1`.

Thanks for your help !

**Comment by jarthod** [comment]
Hello, I just had a similar problem again with a unicode domain name this time:
```
Error parsing 'To': Illegal email domain 'hölle.games' in address 'rowan.jenkins@hölle.games'.
```
This address is also valid RFC822 according to http://sphinx.mythic-beasts.com/~pdw/cgi-bin/emailvalidate.

Could you please clarify if there is some reason why the postmark gem does not allow unicode hostnames?
Shall each clients implement punycode transformation on their end?

Thanks!

**Comment by ibalosh** [comment]
Hi @jarthod 

the errors mentioned are not Postmark gem library related. The errors are coming straight from Postmark API, which is not supporting unicode email addresses at the moment. I suggest contacting support for more details at https://postmarkapp.com/contact

Igor

**Comment by jarthod** [comment]
Thanks for the update @ibalosh!
I did contact support about this a couple days ago, that is likely why you are answering me now :)
I'll wait more for their response then.

**Comment by jarthod** [comment]
**Official answer**: For the record for people looking at this later, the support confirmed that unicode hostname are not supported by the API and the client has to convert the hostname part to punycode before sending to Postmark (there are internal discussions around adding unicode support). 

Also @ibalosh what about the first reported issue with display name `//UwU\\`: "Error parsing 'To': Unclosed quoted string". This one is not related to unicode but rather some parsing/encoding issue. It is also related to the API? anything we can do on our side to circumvent this problem?

**Comment by ibalosh** [comment]
Hi @jarthod 

Related to `//UwU\\` this is also API related issue. Please send that one to customer support, so that fix is requested on the API (send service) side. The issue occurs because of `\\` before email address (at the end of the name), but backend developer team will know better what's causing it on API/send service. If these characters are removed parsing will pass.

Gem only sends requests to the API. API is the one that handles them and if request throws and error, Postmark Gem will return to customer the error within specific error class.  Issue #107 is related to improvements to the gem (one of them being raising Email specific errors when parsing the API error responses). These errors are still coming from the API itself, they are just going to be classified better by the Postmark Gem.

**Comment by jarthod** [comment]
Ok great, thanks for your response :bow:

**Comment by Archanian** [comment]
Hi @jarthod - this is a limitation of the address tokenizer used by the API - display names ending in `\\` will fail due to the way we handle quoted strings, specifically allowing escaped values within such strings (ie. `"Display Name \"Bob\""` is allowed as a display name).

Despite this behaviour not being strictly conforming to the spec, it is unfortunately not something that is easily resolved without a major change to the tokenizer, which has other implications. We are aware of this limitation and it is in our backlog, but for the time being you'll need to work around this edge case.

**Comment by jarthod** [comment]
@Archanian ok thanks! I can prevent the cases I found (e.g. `"\\"` at the end or `"\\ "`) but I suppose there will be more failing cases? any idea of other patterns I should be careful about?
